### ISSUE TITLE
Unable to use GitHub Secrets in forked Actions

### ISSUE THREAD

**Issue by patmigliaccio** [oppielabs/create-envfile#1]
Basically renders this action entirely ineffective until the `ENV_FILE` secret can be decrypted from a fork (e.g. the `uses` property in a Github workflow).

Otherwise, the only mitigating solution is to execute the `create-envfile.py` directly in the local repository’s workflow.

```yaml 
jobs:
  setup-build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create .env file
        env:
          # .env (Base64)
          ENV_FILE: ${{ secrets.ENV_FILE }}
          FILE_NAME: .env
        run: |
          python ./.github/scripts/create-envfile.py
```

**References**
* https://github.community/t5/GitHub-Actions/Allow-secrets-to-be-shared-with-forks-from-trusted-Actions/m-p/34278#M1862
